### ISSUE TITLE
Twitch API - PubSub is being shut down on April 14, 2025

### ISSUE THREAD

**Issue by JustDerb** [JustDerb/RoR2-VsTwitch#64]
Hello,

We’ve identified that your Twitch application below has used the Twitch legacy PubSub system in the last month. As a courtesy, we wanted to send a reminder that [PubSub is deprecated](https://discuss.dev.twitch.com/t/legacy-pubsub-deprecation-and-shutdown-timeline/58043) and action may be required to minimize disruption to your application before the final shutdown on **April 14, 2025**.

**Application Name:** RoR2-VsApp
**Client ID:** ms931m917okbj4hu8l230hejiagie0
**Twitch Account User ID:** [redacted]
**PubSub Topics:** channel-bits-events-v2, channel-points-channel-v1

The successor for real-time events on Twitch is EventSub. To help developers migrate from legacy PubSub to EventSub, a [dedicated migration guide](https://dev.twitch.tv/docs/pubsub/migration/) is available to explain the differences in implementation and the equivalent topics.

# Phased Shutdown Approach
Leading up to the shutdown date, intensional shutdown windows have been established to signal the need for migrating to EventSub. For the most up-to-date schedule, please refer to the announcement linked above. At this time, the first phased shutdown windows will be for 1 hour on February 10, 2025 starting at 11:00AM PST. During this window, new LISTEN requests will be rejected while existing connections will continue to receive events.

# Questions and Assistance
If you have questions regarding the legacy PubSub shutdown, please feel free to comment on the announcement post linked above, or join the [TwitchDev Discord server](https://link.twitch.tv/devchat) and inquire in the #pubsub-help channel under “Migration & Deprecation.”

Thank you.

**Comment by JustDerb** [comment]
@meburningslime if you have some time, would you be willing to test this new version out? Testing requires someone with Channel Points enabled. Let me know!

**Comment by meburningslime** [comment]
@JustDerb I'll be on it soon!

**Comment by JustDerb** [comment]
@meburningslime here's the updated mod with PubSub removed, and EventSub added. I've tested a bit but the only thing that I cannot test is:

- Bit events (someone sends bits in the channel - if you are live on Twitch i am happy to send some over to test 😄 )
- Channel Points events (someone redeems channel points in the channel)

[JustDerb-Vs_Twitch-EventSub-v1.zip](https://github.com/user-attachments/files/19145050/JustDerb-Vs_Twitch-EventSub-v1.zip)

Hopefully this works out of the box 🤞

**Comment by meburningslime** [comment]
Working on it now 👍

**Comment by meburningslime** [comment]
[LogOutput.log](https://github.com/user-attachments/files/19234677/LogOutput.log)

sadly nothing works for channel points. I will continue to test this and see if I can figure out why. No obvious response from log.

I will note both that I cannot find where to check my twitch info in the mod and that it does not appear in the configs. It remembered my channel though and was able to auto-connect for item voting. I am currently going through the files in the mod to attempt to manually troubleshoot it.

**Comment by JustDerb** [comment]
@meburningslime I realized the there was some incompatibilities with the newer TwitchLib library and the libraries Risk of Rain 2 are using. I was able to leverage the `channel.chat.message` EventSub subscription to test things a bit, so it was a bit easier to figure out where things might be going wrong with the `channel.channel_points_custom_reward_redemption.add` EventSub subscription.

The main issue was with the version of `System.Text.Json` that Risk of Rain 2 uses (and TwitchLib assumes a different version):
```c#
// Not found - do not use! (TwitchLib uses this)
public static TValue? Deserialize<TValue>(ReadOnlySpan<char>, JsonSerializerOptions)
// Use this instead
public static TValue? Deserialize<TValue>(string, JsonSerializerOptions)
```

Here's v2 of the mod! Hopefully this works 🤞 

[JustDerb-Vs_Twitch-EventSub-v2.zip](https://github.com/user-attachments/files/19266902/JustDerb-Vs_Twitch-EventSub-v2.zip)

**Comment by JustDerb** [comment]
@meburningslime just checking in - were you able to find some time to test this?

**Comment by meburningslime** [comment]
Hey, I am very sorry I got pretty busy quickly. I tried the mod out and the channel point redemptions still don't work. I went through all the setup again to make sure it wasnt me and nothing.

[LogOutput.log](https://github.com/user-attachments/files/19616693/LogOutput.log)

**Comment by JustDerb** [comment]
No worries! Okay, yeah its the issue I thought I fixed:

```
[Info   :   Console] dbug: TwitchLib.EventSub.Websockets.EventSubWebsocketClient[1180592680]
      System.MissingMethodException: Method not found: !!0 System.Text.Json.JsonSerializer.Deserialize<!0>(System.ReadOnlySpan`1<char>,System.Text.Json.JsonSerializerOptions)
        at TwitchLib.EventSub.Websockets.EventSubWebsocketClient.HandleNotification (System.String message, System.String subscriptionType) [0x00020] in <0d174c52648f484989502ec50c5e3519>:IL_0020 
```

Let me look through again and try to figure out why it's still calling that function...

**Comment by JustDerb** [comment]
Since we're past the deprecation date (April 14, 2025), I went ahead and tried to remove all references of `public static TValue? Deserialize<TValue>(ReadOnlySpan<char>, JsonSerializerOptions)` from TwitchLib and submitted it to the Thunderstore. The new published version is `JustDerb-Vs_Twitch-1.1.1`.

Let me know if you still are having issues!

**Comment by meburningslime** [comment]
[LogOutput.log](https://github.com/user-attachments/files/20128371/LogOutput.log)

Hello,
unfortunately the channel points still do not work. It looks like they aren't being registered at all. I don't know if you know of this or if this is exactly what you are using, but have you heard of Twurple? It works great for my twitch bots. 
https://twurple.js.org/docs/examples/chat/basic-bot.html

**Comment by JustDerb** [comment]
twurple is a JavaScript library, whereas I need a C# library. I think Risk of Rain 2's libraries are showing there age while I need the latest of TwitchLib.

I think at this point, given I'm only leveraging a couple WebSocket API's from Twitch I might just try to leverage the built-in C# WebSocket client and write my own small thing to make this work. Most of the issues around Twitch have been from TwitchLib - no fault to them... it's just moving faster in terms of dependencies versus the game.

**Comment by JustDerb** [comment]
Okay, I took some time to rewrite the WebSocket client internally and got a good MVP ready.

@meburningslime @esporola feel free to try this one out and report back if you find any issues (or not)!

[JustDerb-Vs_Twitch-EventSub-v3.zip](https://github.com/user-attachments/files/20429223/JustDerb-Vs_Twitch-EventSub-v3.zip)

**Comment by meburningslime** [comment]
I am both shocked and impressed at your skill, it works impeccably! I will be streaming this today so I can report any bugs to you soon. It works fine from my limited testing

**Comment by JustDerb** [comment]
@meburningslime thanks, I'm releasing this under the 1.1.2 version! The WebSocket client has some missing features, but based on your recent Twitch stream I was watching it looks like it worked enough to release it to everyone (given that the current version is completely broken).

**Comment by esporola** [comment]
i got to test it today, it was working perfecly, thx for the update :)
